name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - master

jobs:
  tests:
    name: instant-meilisearch-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker setup
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key='masterKey'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Run ESM demo
        run: yarn test:demo:esm
      - name: Run Node.js demo
        run: yarn test:demo:nodejs
      - name: Run Browser demo
        run: yarn test:demo:browser

  style:
    name: instant-meilisearch-style-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Tests style
        run: yarn lint

  builds:
    name: instant-meilisearch-playground-builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests Vue Build
        run: yarn test:playground:vue
      - name: Run tests React Build
        run: yarn test:playground:react
