name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn --dev && yarn --cwd ./playgrounds/react
      - name: Test develop no-reload
        uses: cypress-io/github-action@v2
        with:
          start: yarn build:playground:start
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
  tests:
    name: integration-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker setup
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key='masterKey'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Run env tests
        run: yarn test:env
      - name: Run env tests
        run: yarn test:env


  style:
    name: style-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Tests style
        run: yarn lint

  builds:
    name: playground-builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run Playgrounds Builds
        run: yarn test:playgrounds
